# Application
spring.application.name=library-management-system

# Env
# export SPRING_PROFILES_ACTIVE=prod
spring.profiles.active=dev

# SQL
spring.sql.init.mode=never

# JPA/Hibernate
spring.jpa.open-in-view=false

# Jackson
spring.jackson.mapper.allow-coercion-of-scalars=false

# MVC
spring.web.resources.add-mappings=false
#spring.mvc.throw-exception-if-no-handler-found=true # Deprecated

# Server
server.port=8080
